```{r, echo=FALSE, purl=FALSE, message = FALSE}
knitr::opts_chunk$set(results='hide', comment = "#>", purl = FALSE)
library(shiny)
suppressPackageStartupMessages(library(plotly))
## needed to run this to have shiny show up in the Rmd:
## (https://cran.r-project.org/web/packages/webshot/README.html)
#install.packages("webshot")
#webshot::install_phantomjs()
## "phantomjs has been installed to /Users/cengel/Library/Application Support/PhantomJS"
## Error: "appshot of Shiny app objects not yet supported" :( is that in bookdown??
```

# Interactive graphs

> Learning Objectives
>
> * Be aware of R interactive graphing capabilities
> * Understand the basic structure of a shiny app

------------

## plotly


```{r load-plotly, eval=FALSE}
library(plotly)
```


Using the `ggplotly` function: 

```{r ggplotly-cars, results='show', message = FALSE, warning=FALSE}
p <- ggplot(cars, aes(speed, dist)) + geom_point()
ggplotly(p)
```

(dev. version of ggplot2 now has a `ggplotly()` function)


Using the `plot_ly` function:

```{r plotly-cars, results='show'}
library(plotly)
plot_ly(cars, x = ~speed, y = ~dist, type = "scatter", mode = "markers")
```


## shiny

https://cengel.shinyapps.io/shiny_demo/

```{r shiny-cars, eval=FALSE}
library(shiny)
library(ggplot2)
inputPanel(
    sliderInput("speed_range", 
        label = "Range of Speed:",
        min = min(cars$speed), 
        max = max(cars$speed), 
        value = range(cars$speed)))

renderPlot({
    cars_sel <- subset(cars, speed >= input$speed_range[1] & 
                           speed < input$speed_range[2])
    ggplot(cars_sel, aes(speed, dist)) + geom_point()})
```


For a more comprehensive example see: https://cengel.shinyapps.io/RioSlaveMarket/
